version: '3.5'

services:
  api:
    image: posts
    container_name: posts-api
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: npm run dev
